import React from 'react';
import { useGetAllPaySlipsQuery } from '../../services/payslipSlice';
import Loader from '../../common/Loader';
import { Link } from 'react-router-dom';

const PayslipTable = ({ searchTerm }) => {
  const { data: payslips, isLoading, isError } = useGetAllPaySlipsQuery();

  if (isLoading) return <Loader />;
  if (isError) return <div>Error loading payslip records</div>;

  const filteredPayslips = payslips?.filter((payslip) =>
    payslip.generatedBy.toLowerCase().includes(searchTerm.toLowerCase()),
  );

  return (
    <div className="overflow-x-auto">
      <table className="min-w-full bg-white dark:bg-boxdark">
        <thead>
          <tr>
            <th className="py-2 px-4 border-b border-slate-300 dark:border-slate-600">
              ID
            </th>
            <th className="py-2 px-4 border-b border-slate-300 dark:border-slate-600">
              Payroll ID
            </th>
            <th className="py-2 px-4 border-b border-slate-300 dark:border-slate-600">
              Slip Date
            </th>
            <th className="py-2 px-4 border-b border-slate-300 dark:border-slate-600">
              Generated By
            </th>
            <th className="py-2 px-4 border-b border-slate-300 dark:border-slate-600">
              Created At
            </th>
            <th className="py-2 px-4 border-b border-slate-300 dark:border-slate-600">
              Actions
            </th>
          </tr>
        </thead>
        <tbody>
          {filteredPayslips?.map((payslip) => (
            <tr key={payslip.id}>
              <td className="py-2 px-4 border-b border-slate-300 dark:border-slate-600">
                {payslip.id}
              </td>
              <td className="py-2 px-4 border-b border-slate-300 dark:border-slate-600">
                {payslip.payrollId}
              </td>
              <td className="py-2 px-4 border-b border-slate-300 dark:border-slate-600">
                {payslip.slipDate?.slice(0, 10)}
              </td>
              <td className="py-2 px-4 border-b border-slate-300 dark:border-slate-600">
                {payslip.generatedBy}
              </td>
              <td className="py-2 px-4 border-b border-slate-300 dark:border-slate-600">
                {payslip.created_at?.slice(0, 10)}
              </td>
              <td className="py-2 px-4 border-b border-slate-300 dark:border-slate-600">
                <Link
                  to={`/payslips/view/${payslip.id}`}
                  className="text-primary hover:underline"
                >
                  View
                </Link>
                <Link
                  to={`/payslips/edit/${payslip.id}`}
                  className="ml-2 text-primary hover:underline"
                >
                  Edit
                </Link>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

export default PayslipTable;
