import { PDFDocument, rgb } from 'pdf-lib';

export const createPDF = async (paySlip: any) => {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([600, 400]);
  const { height } = page.getSize();

  page.drawText(`Pay Slip ID: ${paySlip.id}`, { x: 50, y: height - 100, size: 30, color: rgb(0, 0, 0) });
  page.drawText(`Payroll ID: ${paySlip.payrollId}`, { x: 50, y: height - 150, size: 20, color: rgb(0, 0, 0) });
  page.drawText(`Slip Date: ${paySlip.slipDate}`, { x: 50, y: height - 200, size: 20, color: rgb(0, 0, 0) });
  page.drawText(`Generated By: ${paySlip.generatedBy}`, { x: 50, y: height - 250, size: 20, color: rgb(0, 0, 0) });

  return await pdfDoc.save();
};
